---
- hosts: localhost
  tasks:
  - name: Remove any previously created UC backups
    shell: |
      source ~/stackrc
      openstack container delete undercloud-backups --recursive || true
      openstack container delete undercloud-backups_segments --recursive || true
    ignore_errors: True
  - name: Create UC backup
    shell: |
      source ~/stackrc
      openstack undercloud backup --add-path /etc/ --add-path /root/ --add-path /var/lib/glance/ --add-path /var/lib/docker/ --add-path /var/lib/registry/ --add-path /srv/node/
