---
- hosts: localhost
  tasks:

  - name: Print destroy warning.
    vars:
      msg: |
        We are about to destroy the UC, as we are not
        moving outside the UC the backup tarball, we will
        download it and unzip it in a temporary folder to
        recover the UC using those files.
    debug:
      msg: "{{ msg.split('\n') }}"

  - name: Make sure the temp folder used for the restore does not exists
    become: true
    file:
      path: "/var/tmp/test_bk_down"
      state: absent

  - name: Create temp folder to unzip the backup
    become: true
    file:
      path: "/var/tmp/test_bk_down"
      state: directory
      owner: "stack"
      group: "stack"
      mode: "0775"
      recurse: "yes"

  - name: Download the UC backup to a temporary folder (After breaking the UC we won't be able to get it back)
    shell: |
      source ~/stackrc
      cd /var/tmp/test_bk_down
      openstack container save undercloud-backups

  - name: Unzip the backup
    become: true
    shell: |
      cd /var/tmp/test_bk_down
      tar -xvf UC-backup-*.tar
      gunzip *.gz
      tar -xvf filesystem-*.tar

  - name: Make sure stack user can get the backup files
    become: true
    file:
      path: "/var/tmp/test_bk_down"
      state: directory
      owner: "stack"
      group: "stack"
      mode: "0775"
      recurse: "yes"

  - name: Remove mariadb
    become: true
    yum: pkg={{ item }}
         state=absent
    with_items:
      - mariadb
      - mariadb-server

  - name: Remove files
    become: true
    file:
      path: "{{ item }}"
      state: absent
    with_items:
      - /root/.my.cnf
      - /var/lib/mysql
