---
- hosts: localhost
  tasks:

  - name: Remove mariadb
    become: true
    yum: pkg={{ item }}
         state=absent
    with_items:
      - mariadb
      - mariadb-server

  - name: Remove files
    become: true
    file:
      path: "{{ item }}"
      state: absent
    with_items:
      - /root/.my.cnf
      - /var/lib/mysql
