---
- hosts: localhost
  tasks:
    - name: Synchronize the stack user's folder
      synchronize:
        src: /var/tmp/test_bk_down/home/stack/
        dest: /home/stack/
    
    - name: Install mariadb and python-tripleoclient
      become: true
      yum: pkg={{ item }}
           state=present
      with_items:
        - mariadb
        - mariadb-server
        - python-tripleoclient

    - name: Restart MariaDB
      become: true
      service: name=mariadb state=restarted

    - name: Restore the backup DB
      shell: mysql -uroot -e"set global max_allowed_packet = 1073741824;"

    - name: Restore the backup DB
      shell: cat /var/tmp/test_bk_down/all-databases-*.sql | sudo mysql

    - name: Restart MariaDB to perms to refresh
      become: true
      service: name=mariadb state=restarted

    - name: Register root password
      become: true
      shell: cat /var/tmp/test_bk_down/root/.my.cnf | grep -m1 password | cut -d'=' -f2 | tr -d "'"
      register: oldpass

    - name: Clean root password from MariaDB to reinstall the UC
      shell: |
        mysqladmin -u root -p{{ oldpass.stdout }} password ''

    - name: Clean users
      become: true
      mysql_user: name="{{ item }}" host_all="yes" state="absent"
      with_items:
        - ceilometer
        - glance
        - heat
        - ironic
        - keystone
        - neutron
        - nova
        - mistral
        - zaqar
   
    - name: Reinstall the undercloud
      shell: |
        openstack undercloud install
