---
- hosts: localhost
  tasks:
    - name: Install required packages if not installed
      become: true
      yum: pkg={{ item }}
           state=present
      with_items:
        - unzip
        - wget
        - ansible
        - MySQL-python
        
    - name: Synchronize the stack user's folder
      synchronize:
        src: /var/tmp/test_bk_down/home/stack/
        dest: /home/stack/
        
    - name: Synchronize haproxy config file
      become: true
      synchronize:
        src: /var/tmp/test_bk_down/etc/haproxy/
        dest: /etc/haproxy/

    - name: Synchronize cert files
      become: true
      synchronize:
        src: /var/tmp/test_bk_down/etc/pki/instack-certs/
        dest: /etc/pki/instack-certs/

    - name: Create hieradata folder
      become: true
      file:
        path: /etc/puppet/hieradata/
        state: directory
    
    - name: Synchronize hieradata
      become: true
      synchronize:
        src: /var/tmp/test_bk_down/etc/puppet/hieradata/
        dest: /etc/puppet/hieradata/

    - name: Refresh certs
      become: true
      shell: |
        sudo mkdir -p /etc/pki/instack-certs || true
        sudo cp /home/stack/undercloud.pem /etc/pki/instack-certs
        sudo semanage fcontext -a -t etc_t "/etc/pki/instack-certs(/.*)?"
        sudo restorecon -R /etc/pki/instack-certs
        sudo cp cacert.pem /etc/pki/ca-trust/source/anchors/
        sudo update-ca-trust extract

    - name: Install mariadb and python-tripleoclient
      become: true
      yum: pkg={{ item }}
           state=present
      with_items:
        - mariadb
        - mariadb-server
        - python-tripleoclient

    - name: Restart MariaDB
      become: true
      service: name=mariadb state=restarted

    - name: Allow restore big dump DB files
      shell: mysql -uroot -e"set global max_allowed_packet = 1073741824;"

    - name: Restore the backup DB
      shell: cat /var/tmp/test_bk_down/all-databases-*.sql | sudo mysql

    - name: Restart MariaDB to perms to refresh
      become: true
      service: name=mariadb state=restarted

    - name: Register root password
      become: true
      shell: cat /var/tmp/test_bk_down/root/.my.cnf | grep -m1 password | cut -d'=' -f2 | tr -d "'"
      register: oldpass

    - name: Clean root password from MariaDB to reinstall the UC
      shell: |
        mysqladmin -u root -p{{ oldpass.stdout }} password ''

    - name: Clean users
      become: true
      mysql_user: name="{{ item }}" host_all="yes" state="absent"
      with_items:
        - ceilometer
        - glance
        - heat
        - ironic
        - keystone
        - neutron
        - nova
        - mistral
        - zaqar
   
    - name: Reinstall the undercloud
      shell: |
        openstack undercloud install
