---
- hosts: localhost
  tasks:
    - name: Install mariadb
      become: true
      yum: pkg={{ item }}
           state=present
      with_items:
        - mariadb
        - mariadb-server

    - name: Restart MariaDB
      become: true
      service: name=mariadb state=restarted

    - name: Restore the backup DB
      shell: cat /var/tmp/test_bk_down/all-databases-*.sql | sudo mysql

    - name: Clean users
      become: true
      mysql_user: name="{{ item }}" host_all="yes" state="absent"
      with_items:
        - ceilometer
        - glance
        - heat
        - ironic
        - keystone
        - neutron
        - nova
        - mistral
        - zaqar
