---
- hosts: localhost
  tasks:
  
  - name: Make sure the time is synchronized
    become: true
    shell: |
      yum install -y ntp
      chkconfig ntpd on
      service ntpd stop
      ntpdate pool.ntp.org
      service ntpd restart
      
  - name: Install required packages if not installed
    become: true
    yum: pkg={{ item }}
         state=present
    with_items:
      - unzip
      - wget
      - MySQL-python

  - name: Remove any previously created UC backups
    shell: |
      source ~/stackrc
      openstack container delete undercloud-backups --recursive || true
      openstack container delete undercloud-backups_segments --recursive || true
    ignore_errors: True

  - name: Create UC backup
    shell: |
      source ~/stackrc
      openstack undercloud backup --add-path /etc/ --add-path /root/ --add-path /var/lib/glance/ --add-path /var/lib/docker/ --add-path /var/lib/registry/ --add-path /srv/node/
      # missing /var/lib/certmonger
      # Backup all /var/lib/
      # openstack undercloud backup --add-path /etc/ --add-path /root/ --add-path /var/lib/ --add-path /srv/node/
